# Generated by Django 4.1.7 on 2023-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGo_App', '0002_alter_job_options_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_finder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_poster',
            field=models.BooleanField(default=False),
        ),
    ]
