# Generated by Django 4.1.7 on 2023-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGo_App', '0003_newuser_is_finder_newuser_is_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='weburl',
            field=models.URLField(blank=True, max_length=40, null=True),
        ),
    ]
